spring:
    datasource:
        url: jdbc:mysql://localhost:3306/file_extension_blocker
        username: root
        password: root1234
jpa:
    hibernate:
        ddl-auto: update
    show-sql: true